$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  genome:
    type: object
    properties:
      ref:
          type: string
      fai:
          type: string
      gff:
          type: string
      gff_idx:
          type: string
      dict:
          type: string
      mills:
          type: string
      mills_idx:
          type: string
      omni:
          type: string
      omni_idx:
          type: string
      g1k:
          type: string
      g1k_idx:
          type: string
      dbsnp:
          type: string
      dbsnp_idx:
          type: string

  warpper_mirror_prefix:
    type: string

  fastq:
    type: object
    properties:
      pe:
        type: boolean
      platform:
        type: string
        enum: ["CAPILLARY", "LS454", "ILLUMINA", "SOLID", "HELICOS", "IONTORRENT", "ONT", "PACBIO"]
      omics:
        type: string
        enum: ["WGS", "WES"]

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - picard

required:
  - samples
  - genome
  - warpper_mirror
  - filtering
  - processing
  - params
